### ISSUE TITLE
Unable to compile on Solaris 11

### ISSUE THREAD

**Issue by nazunalika** [jhrozek/pam_hbac#97]
Hello. Please forgive me if there are already packaged versions of the module for Solaris 10 and Solaris 11. I'm trying to get the module to compile based on the 1.1 release, but running into a bit of a snag. I'm not really keen on solving compiling issues on Solaris. Attached is the terminal output.

I'm not sure if this is an issue with my system or maybe I need some libraries.
[info.txt](https://github.com/jhrozek/pam_hbac/files/948404/info.txt)

**Comment by jhrozek** [comment]
The 1.1 release should support both Solaris 10 and Solaris 11, although I tested myself only on 11 and Omios. There was another user who reported that 1.1 worked for him on Solaris 10, though.

Could you please attach or paste config.log? It’s a file generated after you run “configure”. I would suggest to first focus on Solaris 11, because there I’ll be able to test the same OS myself locally.

**Comment by nazunalika** [comment]
config.log attached here - let me know if you need any other logs that I can provide.

**Comment by nazunalika** [comment]
[config.txt](https://github.com/jhrozek/pam_hbac/files/949042/config.txt)

**Comment by jhrozek** [comment]
I'm sorry for the late reply. Yes, I'm able to reproduce the problem now. We must have broken it when adding support for HP-UX or for Omnios.

I'll work on a fix.

**Comment by jhrozek** [comment]
I hope I fixed this, at least for me the current master now builds on both Solaris 11 and Omnios. I dont have access to Solaris 10, sorry.

Could you try the current master?

Thank you very much for reporting this bug.

**Comment by nazunalika** [comment]
It compiles on Solaris 11! Thank you for looking into this! I'll try testing 10 when the next work week starts. 

(Forgive me if commenting here re-opens this)
